clc;
t = 0:0.0005:1; 
xa = cos(2*pi*5*t);
subplot(4,1,1);
plot(t,xa);
grid on; 
xlabel('Time, msec');
ylabel('Amplitude');
title('Continuous-time signal x_{a}(t) at f= 5 hz'); 
xb = cos(2*pi*10*t);
subplot(4,1,2);
plot(t,xb);
grid on; 
xlabel('Time, msec');
ylabel('Amplitude');
title('Continuous-time signal x_{a}(t) at f= 10 hz');  
fs =20;
T = 1/fs;
n = 0:T:1; 
xs = cos(2*pi*10*n);
k = 0:length(n)-1;
subplot(4,1,3),stem(k,xs); 
grid on;
xlabel('Time index n');
ylabel('Amplitude');
title('Discrete-time signal x[n] at fs=20 Hz and f=10 Hz'); 
fs =50;
T = 1/fs;
n = 0:T:1; 
xs = cos(2*pi*10*n);
k = 0:length(n)-1;
subplot(4,1,4),stem(k,xs); 
grid on;
xlabel('Time index n');
ylabel('Amplitude');
title('Discrete-time signal x[n] at fs=50 Hz >> f and f=10 Hz'); 
